# Generated by Django 5.0.1

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200)),
                ('street_address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=200)),
                ('recipient_first_name', models.CharField(max_length=100)),
                ('recipient_last_name', models.CharField(max_length=100)),
                ('recipient_street', models.CharField(max_length=200)),
                ('recipient_city', models.CharField(max_length=100)),
                ('recipient_state', models.CharField(max_length=100)),
                ('recipient_zip', models.CharField(max_length=20)),
                ('recipient_country', models.CharField(max_length=2)),
                ('box_size', models.CharField(choices=[('small', "Small (up to 6')"), ('medium', "Medium (6' - 8')"), ('large', "Large (8'+)")], max_length=10)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_reference', models.CharField(blank=True, max_length=100)),
                ('service', models.CharField(choices=[('door-to-door', 'Door to Door'), ('airport-to-airport', 'Airport to Airport')], max_length=20)),
                ('additional_info', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]