# Generated by Django 5.2.5 on 2025-08-08 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardshipper', '0005_add_shipping_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='recipient_country',
            field=models.CharField(max_length=100),
        ),
    ]
