# Generated by Django 5.2.5 on 2025-08-10 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardshipper', '0006_alter_booking_recipient_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='shipping_rate_user',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
